name: Desktop Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-desktop:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build desktop
        run: gradlew.bat desktop:jpackageImage

      - name: Upload desktop build
        uses: actions/upload-artifact@v4
        with:
          name: ERPD-desktop
          path: desktop/build/jpackage/
